### ISSUE TITLE
update to py-moneyed >= 2.0

### ISSUE THREAD

**Issue by elementace** [UpliftAgency/graphene-djmoney#5]
Hi Team, 
py-moneyed dropped moneyed.localization in version 2.0. 
django-money has required py-money >= 1.2 since django-money 2.0 (now stable on 3.0).

Do you have a scope on what would be required to update graphene-djmoney for py-moneyed 2.0?

immediate issue I see is:

`
File "/python_env/lib/python3.9/site-packages/graphene_djmoney/__init__.py", line 3, in <module>

    from . import schema
    
  File "/python_env/lib/python3.9/site-packages/graphene_djmoney/schema/__init__.py", line 1, in <module>
  
    from .types import Currency
    
  File "/python_env/lib/python3.9/site-packages/graphene_djmoney/schema/types.py", line 7, in <module>
  
    from moneyed.localization import CurrencyFormatter
    
ModuleNotFoundError: No module named 'moneyed.localization'
`

Cheers

**Comment by elementace** [comment]
given py-moneyed now relies on babel; is it as simple as replacing 

`
from moneyed.localization import CurrencyFormatter
_cf = CurrencyFormatter()
money_dict["_sign_definition"] = _cf.get_sign_definition(money_dict["code"], get_current_locale())`

with 

`
from babel.numbers import get_currency_symbol
money_dict["_sign_definition"] = get_currency_symbol(money_dict["code"], locale=get_current_locale())
`

babel.numbers.get_currency_symbol(currency, locale='en_US_POSIX')

**Comment by pcraciunoiu** [comment]
@elementace if you'd like to open a PR to support this, I'd be happy to take a look!

**Comment by TylerDavey** [comment]
See this [PR](https://github.com/UpliftAgency/graphene-djmoney/pull/6). 
Changes were mostly as described above, but also removed references to suffix and changed _sign_definition from a tupple to a string in get_sign_definition.

**Comment by pcraciunoiu** [comment]
@TylerDavey I see you ended up closing it, what changed?

Why remove suffix?

**Comment by TylerDavey** [comment]
@pcraciunoiu not sure how that happened, I've restored it now. 
I don't see anywhere to get suffix from the babel library... perhaps that is not an issue since it doesn't really seem to be used anywhere anyway. 
I think we would also need to adjust some of the project reqirements before updating:
```
graphene = ">=2.1.7"
graphql-core = ">=2.1.0"
```

**Comment by pcraciunoiu** [comment]
@TylerDavey thanks for this. I made the suggested requirement change for graphene and graphql-core too, as part of #7 .

**Comment by pcraciunoiu** [comment]
This has been released to pypi as version 0.2.0, though I ended up fixing a few more things to make the PyPI release nicer and patched to 0.2.3
